#服务器相关配置
server:
  port: 9002
  tomcat:
      uri-encoding: UTF-8
      max-threads: 600


#spring相关配置
spring:
#  data:
#    mongodb:
#      host: 192.168.3.86
#      port: 27017
#      database: comprehensiveAppraisal
  devtools:
    restart:
      enabled: true

  session:
    store-type: none
  #redis配置
#  data:
#    mongodb:
#        host: 192.168.2.209
#        database: ceping_zjut
#        port: 27017
  data:
    mongodb:
        host: 192.168.3.1
        database: comprehensiveAppraisal
        port: 27017
  redis:
    host: 39.108.238.199
    port: 6381
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接密码（默认为空）
    password: zgjredistest@2017
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #数据库
  datasource:
#      url: jdbc:mysql://39.108.238.199:3306/ZjutSubsidize?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: zhutao
#      password: 19xbHAO+t6xY8R2tIXSMgssf

      url: jdbc:mysql://192.168.2.209:3306/ceping_zjut?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root

      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  #处理404抛出异常(当出现404直接抛出异常)
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.path}
  http:
      multipart:
        max-request-size: 20MB
        max-file-size: 20MB
  application:
    name: ceping_zjut
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#开启调试模式 打印详细的日志
debug: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xdbigdata.ceping_zjut.domain,com.xdbigdata.ceping_zjut.common.dto
  config-location: classpath:/mybatis-config.xml

  #mapper
  #mappers 多个接口时逗号隔开
mapper:
#  mappers:
#    - com.xdbigdata.subsidize_zjut.mapper.UserMapper
  not-empty: false
  identity: MYSQL

  #pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#file:
#  path: /mnt/sdb/platform/zjut/special-student/

file:
  path: .\upload\

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.108.238.199:8082/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 100000

zuul:
    host:
        connect-timeout-millis: 100000
        socket-timeout-millis: 100000

usercenter:
  url: 39.108.238.199:8086
