#服务器相关配置
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    max-threads: 600

#spring相关配置
spring:
  session:
    store-type: redis
  #redis配置
  redis:
    host: 172.16.15.205
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接密码（默认为空）
    password: xdkjredis@2017
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #数据库
  datasource:
#浙工大服务器数据库连接
      url: jdbc:mysql://172.16.15.207:3306/ZJUTsubsidize?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: zjutSubsidize
      password: YgPykErLzGDxeu2dGTqR
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  #处理404抛出异常(当出现404直接抛出异常)
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.path}
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: subsidize-second-dev

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#开启调试模式 打印详细的日志
debug: true

mybatis:
  mapper-locations: classpath:/com/xdbigdata/ceping_zjut/mapper/*.xml
  type-aliases-package: com.xdbigdata.ceping_zjut.domain,com.xdbigdata.ceping_zjut.common.dto
  config-location: classpath:/mybatis-config.xml

  #mapper
  #mappers 多个接口时逗号隔开
mapper:
#  mappers:
#    - com.xdbigdata.subsidize_zjut.mapper.UserMapper
  not-empty: false
  identity: MYSQL

  #pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

file:
  path: /mnt/sdb/platform/data/subsidize_zjut/upload/
eureka:
  client:
    serviceUrl:
          defaultZone: http://zgd-web-register-01:8080/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 100000

zuul:
    host:
        connect-timeout-millis: 100000
        socket-timeout-millis: 100000